


##################
# Input data
##################
# Directory containing cafeh scripts
cafeh_code_dir="/work-zfs/abattle4/bstrober/tools/cafeh/"

# Directory containing gtex cafeh data (generated by karl)
gtex_cafeh_data="/work-zfs/abattle4/karl/cosie_analysis/output/GTEx/"

# Directory containing summary statistics
# contains file called study_info explaining files and where they came from
summary_stat_dir="/work-zfs/abattle4/bstrober/eqtl_informed_prs/input_data/sumstats/"


# File containing list of gene-names and whether or not they are protein-coding
gene_info_file="/work-zfs/abattle4/lab_data/GTEx_v8/references/gencode.v26.GRCh38.genes.gtf"

#Directory that contains necessary liftover information.
##Specifically, it must contain:
#####1. 'liftOver'   --> the executable
#####2. 'hg19ToHg38.over.chain.gz'   --> for converting from hg19 to hg38
#####2. 'hg38ToHg19.over.chain.gz'   --> for converting from hg38 to hg19
liftover_directory="/work-zfs/abattle4/bstrober/tools/liftOver_x86/"

# File containing gtex tissues to do analysis on and their sample size
gtex_tissue_file="/work-zfs/abattle4/bstrober/eqtl_informed_prs/input_data/gtex_tissue_sample_size_subset.txt"


##################
# Output data
##################
# Output root directory
output_root="/work-zfs/abattle4/bstrober/eqtl_informed_prs/gtex_v8/"

# Directory containing all gtex associations (in cafeh format)
processed_gtex_associations_dir=$output_root"processed_gtex_associations/"

# Directory containing all gtex associations (in cafeh format)
processed_bivariate_cafeh_input_dir=$output_root"processed_bivariate_cafeh_input/"

# Directory containing CAFEH results
bivariate_cafeh_output_dir=$output_root"bivariate_cafeh_output/"










if false; then
sh process_gtex_associations_for_cafeh.sh $processed_gtex_associations_dir $gene_info_file $liftover_directory
fi

trait_name="blood_white_count"
trait_sumstat_file=$summary_stat_dir"bolt_337K_unrelStringentBrit_MAF0.001_v3.blood_WHITE_COUNT.bgen.stats.gz"
sample_size="337491"
if false; then
sh process_data_for_bivariate_cafeh_analysis.sh $trait_name $trait_sumstat_file $gtex_tissue_file $gtex_cafeh_data $processed_gtex_associations_dir $processed_bivariate_cafeh_input_dir $sample_size
fi



if false; then
sh run_cafeh_on_bivariate_data_for_single_trait_shell.sh $trait_name $gtex_tissue_file $processed_bivariate_cafeh_input_dir $bivariate_cafeh_output_dir
fi





